version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mysql
    environment:
      - WAIT_HOSTS=mysql:3306
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
